version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra-container
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=mycassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - cassandra-net

networks:
  cassandra-net: